name: Security - SCA (Dependencies)
on:
  workflow_call:

jobs:
  sca-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy Vulnerability Scanner (FS mode) #trivy para análisis de dependencias
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs" # modo de ejecución de trivy
          scan-ref: "."
          format: "sarif"
          output: "trivy-sca-results.sarif"
          severity: "CRITICAL,HIGH"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: "trivy-sca-results.sarif"
          category: trivy-sca
